### ISSUE TITLE
Can you update the master and tag as v1.0.4

### ISSUE THREAD

**Issue by gkarthiks** [andrewrothstein/ansible-drill#1]
The dependency for role `andrewrothstein.java-oracle-jdk` has been updated with the proper `jre` download URL and tagged as `v2.0.9`, but the master has one patch version lesser (`v2.0.8`) and the latest release of `anible-drill-v1.0.3` has `v2.0.6`.

Because of this, JRE is failing to download.

**Comment by gkarthiks** [comment]
forked and tagged in my repo for now.

**Comment by andrewrothstein** [comment]
updated and tagged as v1.0.5. thanks for pointing that out!
